version: "3.8"
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: kiwi-cc-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/dump.sql:/data/dump.sql
      - ./data/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.0-alpine
    container_name: kiwi-cc-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: kiwi-cc-backend
    ports: 
      - "5000:5000"
    depends_on: 
      - postgres
      - redis
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: kiwi-cc-frontend
    ports: 
      - "3000:3000"
    depends_on: 
      - backend